function createRealTimeARFF(featureVector)

% Turn feature vector to comma-separated and append '?'
allOneString = sprintf('%.0f,' , featureVector);
s = strcat(allOneString,'?');

attributes = [ ...
    '@attribute Zcr numeric\n', ...
    '@attribute Energy numeric\n', ...
    '@attribute EnergyEntropy numeric\n', ...
    '@attribute SpectralCentroid numeric\n', ...
    '@attribute SpectralCentroidSpread numeric\n', ...
    '@attribute SpectralEntropy numeric\n', ...
    '@attribute SpectralFlux numeric\n', ...
    '@attribute SpectralRollOff numeric\n', ...
    '@attribute MFCC1 numeric\n', ...
    '@attribute MFCC2 numeric\n', ...
    '@attribute MFCC3 numeric\n', ...
    '@attribute MFCC4 numeric\n', ...
    '@attribute MFCC5 numeric\n', ...
    '@attribute MFCC6 numeric\n', ...
    '@attribute MFCC7 numeric\n', ...
    '@attribute MFCC8 numeric\n', ...
    '@attribute MFCC9 numeric\n', ...
    '@attribute MFCC10 numeric\n', ...
    '@attribute MFCC11 numeric\n', ...
    '@attribute MFCC12 numeric\n', ...
    '@attribute MFCC13 numeric\n', ...
    '@attribute MFCC14 numeric\n', ...
    '@attribute MFCC15 numeric\n', ...
    '@attribute MFCC16 numeric\n', ...
    '@attribute MFCC17 numeric\n', ...
    '@attribute MFCC18 numeric\n', ...
    '@attribute MFCC19 numeric\n', ...
    '@attribute MFCC20 numeric\n', ...
    '@attribute HarmonicRatio numeric\n', ...
    '@attribute F0 numeric\n', ...
    '@attribute ChromaVector1 numeric\n', ...
    '@attribute ChromaVector2 numeric\n', ...
    '@attribute ChromaVector3 numeric\n', ...
    '@attribute ChromaVector4 numeric\n', ...
    '@attribute ChromaVector5 numeric\n', ...
    '@attribute ChromaVector6 numeric\n', ...
    '@attribute ChromaVector7 numeric\n', ...
    '@attribute ChromaVector8 numeric\n', ...
    '@attribute ChromaVector9 numeric\n', ...
    '@attribute ChromaVector10 numeric\n', ...
    '@attribute ChromaVector11 numeric\n', ...
    '@attribute ChromaVector12 numeric\n', ...
    '@attribute LPC1 numeric\n', ...
    '@attribute LPC2 numeric\n', ...
    '@attribute LPC3 numeric\n', ...
    '@attribute LPC4 numeric\n', ...
    '@attribute LPC5 numeric\n', ...
    '@attribute LPC6 numeric\n', ...
    '@attribute LPC7 numeric\n', ...
    '@attribute LPC8 numeric\n', ...
    '@attribute LPC9 numeric\n', ...
    '@attribute LPC10 numeric\n', ...
    '@attribute LPC11 numeric\n', ...
    '@attribute LPC12 numeric\n', ...
    '@attribute LPC13 numeric\n', ...
    '@attribute LPC14 numeric\n', ...
    '@attribute LPC15 numeric\n', ...
    '@attribute LPC16 numeric\n', ...
    ];

% Create new valence arff
% if exist('rt_valence.arff', 'file') == 7
%     delete('rt_valence.arff');
% end

file_v = fopen('rt_valence.arff','w');

fprintf(file_v,'@relation valence\n\n');
fprintf(file_v,attributes);
fprintf(file_v,'@attribute valence {-2,-1,0,1,2}\n\n');
fprintf(file_v,'@data\n');

fprintf(file_v,s);
fclose(file_v);

% Create new arousal arff
% if exist('rt_arousal.arff', 'file') == 7
%     delete('rt_arousal.arff');
% end

file_a = fopen('rt_arousal.arff','w');
fprintf(file_a,'@relation arousal\n\n');
fprintf(file_a,attributes);
fprintf(file_v,'@attribute arousal {-2,-1,0,1,2}\n\n');
fprintf(file_a,'@data\n');
fprintf(file_a,s);
fclose(file_a);